[package]
name = "rils_bytecode"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = ["crates-io"]
description = "Bytecode compiler, verified format, and virtual machine for Rils"
license.workspace = true
repository.workspace = true

[dependencies]
rils_execution.workspace = true
rils_compiler.workspace = true
rils_host.workspace = true
rils_frontend.workspace = true
rils_builtins.workspace = true
rils_project.workspace = true
rils_driver.workspace = true

[dev-dependencies]
rils_runtime.workspace = true
