pub mod analysis;
pub mod ast;
mod control_flow;
mod error;
pub mod lexer;
pub mod macros;
mod ownership;
pub mod parser;
mod resolution;
pub mod source;
pub mod standard_library;
mod static_type_check;
pub mod token;
mod type_inference;
pub mod types;

pub use error::FrontendError;
pub use lexer::{LexError, lex};
pub use parser::{ParseError, parse};
pub use resolution::{NumericResolutionError, resolve_numeric_literals};
pub use source::Span;
pub use types::{FloatType, FunctionSignature, IntegerType, RuntimeValue, Type};
