use crate::source::Span;

#[derive(Clone, Debug, PartialEq)]
pub enum TokenKind {
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    LeftBracket,
    RightBracket,
    Comma,
    Colon,
    ColonColon,
    Dot,
    DotDot,
    Semicolon,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Dollar,
    Bang,
    Question,
    BangEqual,
    Equal,
    EqualEqual,
    FatArrow,
    Greater,
    GreaterEqual,
    Ampersand,
    Less,
    LessEqual,
    AndAnd,
    OrOr,
    Arrow,
    Identifier(String),
    I8(i8),
    I16(i16),
    I32(i32),
    I64(i64),
    I128(i128),
    Isize(isize),
    U8(u8),
    U16(u16),
    U32(u32),
    U64(u64),
    U128(u128),
    Usize(usize),
    F32(f32),
    F64(f64),
    Char(char),
    Integer(i128),
    Float(f64),
    String(String),
    Let,
    Mut,
    Fn,
    Macro,
    If,
    Else,
    While,
    Loop,
    Match,
    Struct,
    Enum,
    Impl,
    Trait,
    Type,
    For,
    In,
    As,
    Return,
    Break,
    Continue,
    Mod,
    Use,
    Crate,
    Super,
    Pub,
    True,
    False,
    Nil,
    Eof,
}

impl TokenKind {
    pub fn name(&self) -> &'static str {
        match self {
            Self::LeftParen => "`(`",
            Self::RightParen => "`)`",
            Self::LeftBrace => "`{`",
            Self::RightBrace => "`}`",
            Self::LeftBracket => "`[`",
            Self::RightBracket => "`]`",
            Self::Comma => "`,`",
            Self::Colon => "`:`",
            Self::ColonColon => "`::`",
            Self::Dot => "`.`",
            Self::DotDot => "`..`",
            Self::Semicolon => "`;`",
            Self::Plus => "`+`",
            Self::Minus => "`-`",
            Self::Star => "`*`",
            Self::Slash => "`/`",
            Self::Percent => "`%`",
            Self::Dollar => "`$`",
            Self::Bang => "`!`",
            Self::Question => "`?`",
            Self::BangEqual => "`!=`",
            Self::Equal => "`=`",
            Self::EqualEqual => "`==`",
            Self::FatArrow => "`=>`",
            Self::Greater => "`>`",
            Self::GreaterEqual => "`>=`",
            Self::Ampersand => "`&`",
            Self::Less => "`<`",
            Self::LessEqual => "`<=`",
            Self::AndAnd => "`&&`",
            Self::OrOr => "`||`",
            Self::Arrow => "`->`",
            Self::Identifier(_) => "identifier",
            Self::I8(_)
            | Self::I16(_)
            | Self::I32(_)
            | Self::I64(_)
            | Self::I128(_)
            | Self::Isize(_)
            | Self::U8(_)
            | Self::U16(_)
            | Self::U32(_)
            | Self::U64(_)
            | Self::U128(_)
            | Self::Usize(_)
            | Self::Integer(_) => "integer",
            Self::F32(_) | Self::F64(_) | Self::Float(_) => "f64",
            Self::Char(_) => "char",
            Self::String(_) => "string",
            Self::Let => "`let`",
            Self::Mut => "`mut`",
            Self::Fn => "`fn`",
            Self::Macro => "`macro`",
            Self::If => "`if`",
            Self::Else => "`else`",
            Self::While => "`while`",
            Self::Loop => "`loop`",
            Self::Match => "`match`",
            Self::Struct => "`struct`",
            Self::Enum => "`enum`",
            Self::Impl => "`impl`",
            Self::Trait => "`trait`",
            Self::Type => "`type`",
            Self::For => "`for`",
            Self::In => "`in`",
            Self::As => "`as`",
            Self::Return => "`return`",
            Self::Break => "`break`",
            Self::Continue => "`continue`",
            Self::Mod => "`mod`",
            Self::Use => "`use`",
            Self::Crate => "`crate`",
            Self::Super => "`super`",
            Self::Pub => "`pub`",
            Self::True => "`true`",
            Self::False => "`false`",
            Self::Nil => "`nil`",
            Self::Eof => "end of file",
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
}

impl Token {
    pub const fn new(kind: TokenKind, span: Span) -> Self {
        Self { kind, span }
    }
}
