[package]
name = "rils_stdlib"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = ["crates-io"]
description = "Rust source definitions for the Rils standard library"
license.workspace = true
repository.workspace = true

[dependencies]
rils_builtins_macros.workspace = true
