[package]
name = "rils_builtins_macros"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = ["crates-io"]
description = "Compile-time stable IDs and declarations for Rils built-ins"
license.workspace = true
repository.workspace = true
include = ["/Cargo.toml", "/README.md", "/src/**"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
rils_syntax.workspace = true
syn = { version = "2.0", features = ["full"] }
toml.workspace = true
