[package]
name = "rils_builtins"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = ["crates-io"]
description = "Shared built-in API metadata for the Rils toolchain"
license.workspace = true
repository.workspace = true
include = ["/Cargo.toml", "/README.md", "/builtin_ids.toml", "/src/**", "/stdlib/**"]

[dependencies]
rils_builtins_macros.workspace = true
rils_syntax.workspace = true
