[package]
name = "rils_frontend"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = ["crates-io"]
description = "Static analysis and semantic frontend for the Rils scripting language"
license.workspace = true
repository.workspace = true
include = ["/Cargo.toml", "/src/**"]

[dependencies]
rils_builtins.workspace = true
rils_syntax.workspace = true
