[package]
name = "rils_native"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = ["crates-io"]
description = "Runtime-independent registration protocol for Rils native values"
license.workspace = true
repository.workspace = true
include = ["/Cargo.toml", "/README.md", "/src/**"]

[dependencies]
rils_syntax.workspace = true
rils_value.workspace = true
