#!/usr/bin/env python3
"""Generate the low-level C# P/Invoke declarations from rils.h."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ENUM_RE = re.compile(r"enum\s+(RilsStatus|RilsValueTag)\s*\{(.*?)\};", re.DOTALL)
ENTRY_RE = re.compile(r"(RILS_[A-Z0-9_]+)\s*=\s*(\d+)")
FUNCTION_RE = re.compile(
    r"^RILS_API[ \t]+([A-Za-z0-9_]+)[ \t]+(rils_[a-z0-9_]+)\s*\((.*?)\);",
    re.DOTALL | re.MULTILINE,
)


def pascal(value: str) -> str:
    return "".join(part.capitalize() for part in value.split("_") if part)


def enum_source(header: str, c_name: str, prefix: str, underlying: str) -> str:
    match = next((item for item in ENUM_RE.finditer(header) if item.group(1) == c_name), None)
    if match is None:
        raise RuntimeError(f"missing {c_name} in rils.h")
    entries = ENTRY_RE.findall(match.group(2))
    if not entries:
        raise RuntimeError(f"{c_name} has no entries")
    lines = [f"public enum {c_name} : {underlying}", "{"]
    for name, value in entries:
        if not name.startswith(prefix):
            raise RuntimeError(f"unexpected {c_name} entry {name}")
        lines.append(f"    {pascal(name.removeprefix(prefix))} = {value},")
    lines.append("}")
    return "\n".join(lines)


def return_type(c_type: str) -> str:
    return {
        "uint32_t": "uint",
        "uint64_t": "ulong",
        "int32_t": "int",
        "RilsHandle": "ulong",
        "RilsSlice": "NativeSlice",
    }[" ".join(c_type.split())]


def parameter(c_parameter: str) -> str:
    value = " ".join(c_parameter.split())
    patterns = [
        (r"const RilsHostFunction \*(\w+)", lambda name: f"NativeHostFunction* {name}"),
        (r"const RilsHostType \*(\w+)", lambda name: f"NativeHostType* {name}"),
        (r"const RilsHostFunctionV2 \*(\w+)", lambda name: f"NativeHostFunctionV2* {name}"),
        (r"const RilsHostParameter \*(\w+)", lambda name: f"NativeHostParameter* {name}"),
        (r"RilsHandle \*(\w+)", lambda name: f"out ulong {name}"),
        (r"RilsValue \*(\w+)", lambda name: f"out NativeValue {name}"),
        (r"RilsSlice \*(\w+)", lambda name: f"NativeSlice* {name}"),
        (r"size_t \*(\w+)", lambda name: f"out UIntPtr {name}"),
        (r"const RilsValue \*(\w+)", lambda name: f"NativeValue* {name}"),
        (r"uint8_t \*(\w+)", lambda name: f"byte* {name}"),
        (r"RilsHandle (\w+)", lambda name: f"ulong {name}"),
        (r"RilsSlice (\w+)", lambda name: f"NativeSlice {name}"),
        (r"RilsHostDispatcher (\w+)", lambda name: f"NativeHostDispatcher {name}"),
        (r"void \*(\w+)", lambda name: f"IntPtr {name}"),
        (r"uint64_t (\w+)", lambda name: f"ulong {name}"),
        (r"size_t (\w+)", lambda name: f"UIntPtr {name}"),
    ]
    for pattern, render in patterns:
        match = re.fullmatch(pattern, value)
        if match:
            return render(match.group(1))
    raise RuntimeError(f"unsupported C parameter: {value}")


def function_source(header: str) -> str:
    functions = []
    for match in FUNCTION_RE.finditer(header):
        c_return, entry_point, c_parameters = match.groups()
        parameters = [] if c_parameters.strip() == "void" else [
            parameter(item.strip()) for item in c_parameters.split(",")
        ]
        managed_name = pascal(entry_point.removeprefix("rils_"))
        functions.extend(
            [
                f'    [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "{entry_point}")]',
                f"    internal static extern {return_type(c_return)} {managed_name}({', '.join(parameters)});",
                "",
            ]
        )
    if not functions:
        raise RuntimeError("rils.h contains no exported functions")
    return "\n".join(functions).rstrip()


def generate(header: str) -> str:
    status = enum_source(header, "RilsStatus", "RILS_STATUS_", "int")
    tags = enum_source(header, "RilsValueTag", "RILS_VALUE_", "uint")
    functions = function_source(header)
    return f"""// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;

namespace Rils.CSharp
{{

{status}

{tags}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct NativeSlice
{{
    internal byte* Data;
    internal UIntPtr Length;
}}

[StructLayout(LayoutKind.Sequential)]
internal struct NativeValue
{{
    internal RilsValueTag Tag;
    internal uint Reserved;
    internal ulong Low;
    internal ulong High;
}}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct NativeHostFunction
{{
    internal ulong FunctionId;
    internal NativeSlice Name;
    internal NativeSlice Capability;
    internal uint* ParameterTags;
    internal UIntPtr ParameterCount;
    internal RilsValueTag ReturnTag;
    internal uint Reserved;
}}

[StructLayout(LayoutKind.Sequential)]
internal struct NativeHostType
{{
    internal NativeSlice Name;
    internal NativeSlice BaseType;
    internal RilsValueTag TransportTag;
    internal uint Reserved;
}}

[StructLayout(LayoutKind.Sequential)]
internal struct NativeHostParameter
{{
    internal NativeSlice LogicalType;
    internal RilsValueTag TransportTag;
    internal uint Reserved;
}}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct NativeHostFunctionV2
{{
    internal ulong FunctionId;
    internal NativeSlice Name;
    internal NativeSlice Capability;
    internal NativeHostParameter* Parameters;
    internal UIntPtr ParameterCount;
    internal NativeHostParameter ReturnParameter;
    internal uint Receiver;
    internal uint Reserved;
}}

[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
internal unsafe delegate int NativeHostDispatcher(
    IntPtr userData,
    ulong functionId,
    NativeValue* arguments,
    UIntPtr argumentCount,
    NativeValue* outValue,
    NativeSlice* outError);

internal static unsafe class NativeMethods
{{
    internal const string LibraryName = "rils_capi";

{functions}
}}
}}
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated output is stale")
    args = parser.parse_args()

    root = Path(__file__).resolve().parent.parent
    header_path = root / "crates" / "rils_capi" / "include" / "rils.h"
    output_path = root / "crates" / "rils_capi" / "csharp" / "Rils.CSharp" / "Generated" / "NativeMethods.g.cs"
    expected = generate(header_path.read_text(encoding="utf-8"))
    if args.check:
        actual = output_path.read_text(encoding="utf-8") if output_path.exists() else ""
        if actual != expected:
            raise SystemExit(f"generated binding is stale: run python {Path(__file__).name}")
        print(f"{output_path.relative_to(root)} is up to date")
        return 0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(expected, encoding="utf-8", newline="\n")
    print(output_path.relative_to(root))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
